export const MENU_ITEMS = [
  {
    id: '1',
    name: 'Margherita Pizza',
    description: 'Fresh mozzarella, basil, and tomato sauce on a thin crust',
    price: 299,
    category: 'mains' as const,
    image: 'https://images.pexels.com/photos/4206666/pexels-photo-4206666.jpeg?auto=compress&cs=tinysrgb&w=400&h=400&fit=crop',
    vegetarian: true,
    spicy: 0,
    popular: true,
  },
  {
    id: '2',
    name: 'Grilled Chicken Burger',
    description: 'Tender grilled chicken with fresh lettuce and special sauce',
    price: 249,
    category: 'mains' as const,
    image: 'https://images.pexels.com/photos/5537623/pexels-photo-5537623.jpeg?auto=compress&cs=tinysrgb&w=400&h=400&fit=crop',
    vegetarian: false,
    spicy: 1,
    popular: true,
  },
  {
    id: '3',
    name: 'Caesar Salad',
    description: 'Crisp romaine lettuce with parmesan, croutons, and creamy caesar dressing',
    price: 199,
    category: 'appetizers' as const,
    image: 'https://images.pexels.com/photos/2097090/pexels-photo-2097090.jpeg?auto=compress&cs=tinysrgb&w=400&h=400&fit=crop',
    vegetarian: true,
    spicy: 0,
    popular: false,
  },
  {
    id: '4',
    name: 'Chocolate Lava Cake',
    description: 'Warm chocolate cake with a flowing molten center, served with vanilla ice cream',
    price: 199,
    category: 'desserts' as const,
    image: 'https://images.pexels.com/photos/17886668/pexels-photo-17886668.jpeg?auto=compress&cs=tinysrgb&w=400&h=400&fit=crop',
    vegetarian: true,
    spicy: 0,
    popular: true,
  },
  {
    id: '5',
    name: 'Espresso',
    description: 'Strong and rich espresso shot',
    price: 99,
    category: 'beverages' as const,
    image: 'https://images.pexels.com/photos/312418/pexels-photo-312418.jpeg?auto=compress&cs=tinysrgb&w=400&h=400&fit=crop',
    vegetarian: true,
    spicy: 0,
    popular: false,
  },
  {
    id: '6',
    name: 'Paneer Tikka Masala',
    description: 'Soft paneer cubes in creamy tomato-based sauce with aromatic spices',
    price: 349,
    category: 'mains' as const,
    image: 'https://images.pexels.com/photos/6643489/pexels-photo-6643489.jpeg?auto=compress&cs=tinysrgb&w=400&h=400&fit=crop',
    vegetarian: true,
    spicy: 2,
    popular: true,
  },
  {
    id: '7',
    name: 'Tandoori Chicken',
    description: 'Marinated chicken grilled in traditional tandoor oven',
    price: 399,
    category: 'mains' as const,
    image: 'https://images.pexels.com/photos/7974626/pexels-photo-7974626.jpeg?auto=compress&cs=tinysrgb&w=400&h=400&fit=crop',
    vegetarian: false,
    spicy: 2,
    popular: true,
  },
  {
    id: '8',
    name: 'Garlic Bread',
    description: 'Crispy bread with garlic butter and fresh herbs',
    price: 149,
    category: 'appetizers' as const,
    image: 'https://images.pexels.com/photos/5732437/pexels-photo-5732437.jpeg?auto=compress&cs=tinysrgb&w=400&h=400&fit=crop',
    vegetarian: true,
    spicy: 0,
    popular: false,
  },
  {
    id: '9',
    name: 'Fresh Mango Lassi',
    description: 'Refreshing yogurt-based drink with mango pulp',
    price: 129,
    category: 'beverages' as const,
    image: 'https://images.pexels.com/photos/3902882/pexels-photo-3902882.jpeg?auto=compress&cs=tinysrgb&w=400&h=400&fit=crop',
    vegetarian: true,
    spicy: 0,
    popular: false,
  },
];

export const RESTAURANT_INFO = {
  name: process.env.NEXT_PUBLIC_RESTAURANT_NAME || "Vilas's RestoCafe",
  phone: process.env.NEXT_PUBLIC_RESTAURANT_PHONE || '+91-8899776655',
  email: process.env.NEXT_PUBLIC_RESTAURANT_EMAIL || 'hello@restocafe.com',
  address: process.env.NEXT_PUBLIC_RESTAURANT_ADDRESS || 'MG Road, Bengaluru, Karnataka 560001',
  hours: 'Mon-Sun: 10:00 AM - 11:00 PM',
  cuisines: ['Indian', 'Italian', 'Continental'],
};
