export const MENU_ITEMS = [
  {
    id: '1',
    name: 'Margherita Pizza',
    description: 'Fresh mozzarella, basil, and tomato sauce on a thin crust',
    price: 299,
    category: 'mains' as const,
    image: 'https://images.unsplash.com/photo-1604068549290-dea0e4a305ca?w=500&h=500&fit=crop',
    vegetarian: true,
    spicy: 0,
    popular: true,
  },
  {
    id: '2',
    name: 'Grilled Chicken Burger',
    description: 'Tender grilled chicken with fresh lettuce and special sauce',
    price: 249,
    category: 'mains' as const,
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=500&h=500&fit=crop',
    vegetarian: false,
    spicy: 1,
    popular: true,
  },
  {
    id: '3',
    name: 'Caesar Salad',
    description: 'Crisp romaine lettuce with parmesan, croutons, and creamy caesar dressing',
    price: 199,
    category: 'appetizers' as const,
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=500&h=500&fit=crop',
    vegetarian: true,
    spicy: 0,
    popular: false,
  },
  {
    id: '4',
    name: 'Chocolate Lava Cake',
    description: 'Warm chocolate cake with a flowing molten center, served with vanilla ice cream',
    price: 199,
    category: 'desserts' as const,
    image: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=500&h=500&fit=crop',
    vegetarian: true,
    spicy: 0,
    popular: true,
  },
  {
    id: '5',
    name: 'Espresso',
    description: 'Strong and rich espresso shot',
    price: 99,
    category: 'beverages' as const,
    image: 'https://images.unsplash.com/photo-1559056199-641a0ac8b3f4?w=500&h=500&fit=crop',
    vegetarian: true,
    spicy: 0,
    popular: false,
  },
  {
    id: '6',
    name: 'Paneer Tikka Masala',
    description: 'Soft paneer cubes in creamy tomato-based sauce with aromatic spices',
    price: 349,
    category: 'mains' as const,
    image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=500&h=500&fit=crop',
    vegetarian: true,
    spicy: 2,
    popular: true,
  },
  {
    id: '7',
    name: 'Tandoori Chicken',
    description: 'Marinated chicken grilled in traditional tandoor oven',
    price: 399,
    category: 'mains' as const,
    image: 'https://images.unsplash.com/photo-1598103442097-8b74394b95c6?w=500&h=500&fit=crop',
    vegetarian: false,
    spicy: 2,
    popular: true,
  },
  {
    id: '8',
    name: 'Garlic Bread',
    description: 'Crispy bread with garlic butter and fresh herbs',
    price: 149,
    category: 'appetizers' as const,
    image: 'https://images.unsplash.com/photo-1589985643862-1cfc1d82f78d?w=500&h=500&fit=crop',
    vegetarian: true,
    spicy: 0,
    popular: false,
  },
  {
    id: '9',
    name: 'Fresh Mango Lassi',
    description: 'Refreshing yogurt-based drink with mango pulp',
    price: 129,
    category: 'beverages' as const,
    image: 'https://images.unsplash.com/photo-1585518419759-2d27e9ff9c4c?w=500&h=500&fit=crop',
    vegetarian: true,
    spicy: 0,
    popular: false,
  },
];

export const RESTAURANT_INFO = {
  name: process.env.NEXT_PUBLIC_RESTAURANT_NAME || "Vilas's RestoCafe",
  phone: process.env.NEXT_PUBLIC_RESTAURANT_PHONE || '+91-8899776655',
  email: process.env.NEXT_PUBLIC_RESTAURANT_EMAIL || 'hello@restocafe.com',
  address: process.env.NEXT_PUBLIC_RESTAURANT_ADDRESS || 'MG Road, Bengaluru, Karnataka 560001',
  hours: 'Mon-Sun: 10:00 AM - 11:00 PM',
  cuisines: ['Indian', 'Italian', 'Continental'],
};
